### ISSUE TITLE
Request to Refactor var to let and const

### ISSUE THREAD

**Issue by dmcote-1991** [patorjk/JavaScript-Snake#116]
### Proposal: Refactor `var` Declarations to `let` and `const`

I would like to propose a refactor of the code to replace `var` declarations with `let` and `const` where appropriate. This change aims to improve code readability and adhere to modern JavaScript best practices.

#### Proposed Changes
- **Change `var` to `let`**: For variables that are reassigned.
- **Change `var` to `const`**: For variables that are not reassigned after initialization.

#### Benefits
- **Enhanced Readability**: `let` and `const` provide block scope, making the code easier to understand and less prone to errors related to variable scope.
- **Modern Best Practices**: Using `let` and `const` aligns with current JavaScript standards and practices.

#### Example
Here’s a snippet of the code I am referring to:

**Current Code:**
```javascript
var SNAKE = SNAKE || {};
var instanceNumber = 0;
var blockPool = [];
```

### Proposed Changes

I propose changing the code to:

```javascript
const SNAKE = SNAKE || {};
let instanceNumber = 0;
const blockPool = [];
```

### Questions

1. Are there any concerns about making these changes?
2. Is there any additional context or consideration I should be aware of before proceeding?

Thank you for considering this refactor. I believe it will contribute to a cleaner and more maintainable codebase.

**Comment by patorjk** [comment]
Yep, it’s been a while since I’ve used var, this code is just very old (written before those were apart of the language). I’d be fine with such a refactor.

**Comment by dmcote-1991** [comment]
Great! I'll start getting to work on it. Thank you for the opportunity :)

**Comment by dmcote-1991** [comment]
Hi patorjk,

I've created a Pull Request to address issue #116, where I refactored var to let and const. Please take a look when you have a chance!

Thanks!

**Comment by patorjk** [comment]
Looks good, thank you!

**Comment by patorjk** [comment]
https://github.com/all-contributors
please add @dmcote-1991 for code.
