### ISSUE TITLE
Too Fast

### ISSUE THREAD

**Issue by josephworks** [patorjk/JavaScript-Snake#40]
The snake goes too fast and the input lag makes it even worse... I do like the idea of snake java script so please continue working on it. You should add a scoreboard too!

**Comment by Hexyman** [comment]
He isn't on anymore he can't change anything rn. Sorry /:

**Comment by patorjk** [comment]
I'm here, I just don't have much time to work on this. Someone added a scoreboard and it's in this repo, but I wasn't fully happy with it. I wanted to work some more on it but just haven't had the time.

**Comment by josephworks** [comment]
The issue doesn't appear to be fixed in the future.
