### ISSUE TITLE
Social links on bottom of page.

### ISSUE THREAD

**Issue by Joshii01** [patorjk/JavaScript-Snake#76]
Hello there fellas! may i ask how can i remove the social links on the bottom of the page? i would really really love it if you guys would help me out! @patorjk

**Comment by mamamia5x** [comment]
Erase line 675 of js/snake.js file. @Joshii01

**Comment by patorjk** [comment]
@Joshii01 see @mamamia5x's comment above.

**Comment by Joshii01** [comment]
i seem to be having an issue, i removed line 675 which was this: `elmAboutPanel.innerHTML = "<a href='http://patorjk.com/blog/software/' class='snake-link'>more maybe?</a> - <a href='https://github.com/patorjk/JavaScript-Snake' class='snake-link'>source code</a> - <a href='https://www.instagram.com/patorjk/' class='snake-link'>pat's instagram</a>";` but the social links still appear so what should i do?
![image](https://user-images.githubusercontent.com/78946868/108233825-ff28db00-70f8-11eb-9e7d-26fd9fd6b6f3.png)

**Comment by mamamia5x** [comment]
Make sure line 107 says <code><script type="text/javascript" src="./js/snake.js"></script></code> and not
<code><script type="text/javascript" src="./js/min-snake.js"></script></code>

**Comment by Joshii01** [comment]
i checked, yet that didnt change anything it still shows the links 
Here is a picture of the snake.js file on line 675 and also a picture of the index.html at line 107:
![image](https://user-images.githubusercontent.com/78946868/108242475-cd684200-7101-11eb-97be-1156602f2169.png)
![image](https://user-images.githubusercontent.com/78946868/108242548-e2dd6c00-7101-11eb-8e08-91565b46a1d7.png)

**Comment by mamamia5x** [comment]
The script looks right, is it saved right? Right something to the html file like add "test" to line 90.
If it saved and works, it should display test in front of the save button. If it works and the social links don't work, it might be a compiler issue.

**Comment by Joshii01** [comment]
yes it is saved, i wrote test on line 90 in the html file but the social links are still there, here is a picture of the snake game and the html file at line 90: 
![image](https://user-images.githubusercontent.com/78946868/108247004-f3dcac00-7106-11eb-809c-035678d9040b.png)
![image](https://user-images.githubusercontent.com/78946868/108247047-01923180-7107-11eb-85f0-d91011a4b60b.png)

**Comment by Joshii01** [comment]
yes it is saved, but it still shows the social links on the bottom. 
here is a picture of the snake game and the html file at line 90:
![image](https://user-images.githubusercontent.com/78946868/108247192-31d9d000-7107-11eb-975e-9d09a1bd1b8c.png)
![image](https://user-images.githubusercontent.com/78946868/108247249-3ef6bf00-7107-11eb-98d7-c8e1c49beac5.png)

**Comment by mamamia5x** [comment]
My version is here https://javascript-snake-8.mamamia5x.repl.co/
Copy and paste the content at [view-source:https://javascript-snake-8.mamamia5x.repl.co/ ](view-source:https://javascript-snake-8.mamamia5x.repl.co/) into the html file and then copy and paste the content at https://javascript-snake-8.mamamia5x.repl.co/js/snake.js to the js/snake.js file.  
Hopefully this solves the problem.

**Comment by Joshii01** [comment]
I copy pasted that but it still shows the links at the bottom of the page what should i do?
![image](https://user-images.githubusercontent.com/78946868/108249046-72d2e400-7109-11eb-8a6f-4f1209d6d70a.png)

**Comment by mamamia5x** [comment]
I really don't know. . .
Mine works just fine https://javascript-snake-8.mamamia5x.repl.co/
Try using a different compiler (like repl.it)

**Comment by Joshii01** [comment]
ok! let me try that real quick

**Comment by Joshii01** [comment]
for some reason repl.it only shows this when i run the code:
![image](https://user-images.githubusercontent.com/78946868/108251422-3785e480-710c-11eb-86b0-f53c1d9dc59a.png)

**Comment by Joshii01** [comment]
@patorjk please help, i would really like to use this in my website

**Comment by mamamia5x** [comment]
Try replacing the index.html with the original file.

**Comment by mamamia5x** [comment]
if that doesn't work, try doing the original script file and then making line 675 a comment.

**Comment by Joshii01** [comment]
ok! give me a second while i try that

**Comment by Joshii01** [comment]
I tried that but it still would show the links on the bottom
![image](https://user-images.githubusercontent.com/78946868/108257503-bc283100-7113-11eb-8412-8770dff8c425.png)

**Comment by mamamia5x** [comment]
Go to here https://repl.it/@mamamia5x/JavaScript-Snake-8

**Comment by mamamia5x** [comment]
And then just fork it

**Comment by Joshii01** [comment]
ok!

**Comment by Joshii01** [comment]
I tried that but it doesnt seem to be working as well 
![image](https://user-images.githubusercontent.com/78946868/108259538-10341500-7116-11eb-9ee6-60002ae3cfa1.png)

**Comment by mamamia5x** [comment]
Are you on the right site, or are you looking at the official site? 'Cuz if you go to https://javascript-snake-8.mamamia5x.repl.co/ it won't show up.

**Comment by Joshii01** [comment]
I am looking at my site which i am running the code on

**Comment by mamamia5x** [comment]
What is the url to the site?

**Comment by Joshii01** [comment]
http://snakegame.selync.ga/?i=2

**Comment by mamamia5x** [comment]
Alright, it looks like the JS file is messed up. Can you reset the whole site to make it even to the github?

**Comment by Joshii01** [comment]
alright!

**Comment by mamamia5x** [comment]
In JavaScript-Snake-master/ go to script.js and then paste the content in https://javascript-snake-8.mamamia5x.repl.co/js/snake.js

**Comment by Joshii01** [comment]
alright!

**Comment by Joshii01** [comment]
done!

**Comment by mamamia5x** [comment]
Alright, it looks good!

**Comment by Joshii01** [comment]
what should i do know?

**Comment by mamamia5x** [comment]
What do you mean?

**Comment by Joshii01** [comment]
how do i remove the social links now?

**Comment by mamamia5x** [comment]
They're gone 
![image](https://user-images.githubusercontent.com/57536929/108262941-34e6b780-712b-11eb-9d75-cf2d92927d76.png)

**Comment by mamamia5x** [comment]
That's your site

**Comment by Joshii01** [comment]
did you do inspect element? because on my side it shows this:
![image](https://user-images.githubusercontent.com/78946868/108263052-994d4b00-711a-11eb-9fc3-516c63c1b3ca.png)

**Comment by mamamia5x** [comment]
Are you on http://snakegame.selync.ga/?i=2

**Comment by Joshii01** [comment]
Yes

**Comment by mamamia5x** [comment]
It doesn't show the social icons, try going on a different browser

**Comment by Joshii01** [comment]
i only have google chrome right now

**Comment by mamamia5x** [comment]
Alright, but it works completely fine on my end.

**Comment by Joshii01** [comment]
are you sure you didnt inspect element? because how else would you be able to edit the code on my site?

**Comment by mamamia5x** [comment]
I reloaded the page, and it doesn't show anything.

**Comment by Joshii01** [comment]
weird, but may i ask how you edited the code on my site?

**Comment by mamamia5x** [comment]
I didn't (if I would edit it, I would use dev tools).
Open it up in a new tab. http://snakegame.selync.ga/?i=2

**Comment by Joshii01** [comment]
i did, it still shows the links on the bottom

**Comment by mamamia5x** [comment]
Idk what's happening then. Everythings working fine for me.

**Comment by Joshii01** [comment]
so is there anything i can do on my end to fix it?

**Comment by mamamia5x** [comment]
Probably not, or not anything that I know of.

**Comment by Joshii01** [comment]
alright then! thanks for your help and your time! i will try and check the site on some other browsers later on.
